[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
pythonpath = config
addopts = -v --tb=short --cov=account --cov=monitoring --cov=common --cov-report=term-missing
