# Generated by Django 6.0.7 on 2026-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_alerts_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the user receives email incident and recovery alerts.",
            ),
        ),
    ]
