# Generated by Django 6.0.7 on 2026-09-05 11:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("is_up", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="monitoring.monitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["monitor", "-timestamp"],
                        name="monitoring__monitor_703e11_idx",
                    )
                ],
            },
        ),
    ]
