# Generated by Django 6.0.7 on 2026-09-10 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0003_alert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="checkresult",
            new_name="checkresult_monitor_time_idx",
            old_name="monitoring__monitor_703e11_idx",
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["monitor", "is_resolved", "-created_at"],
                name="alert_monitor_resolved_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(fields=["is_active"], name="monitor_is_active_idx"),
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(
                fields=["user", "is_active"], name="monitor_user_active_idx"
            ),
        ),
    ]
