# Generated by Django 6.0.7 on 2026-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitoring",
            "0004_rename_monitoring__monitor_703e11_idx_checkresult_monitor_time_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="interval",
            field=models.PositiveIntegerField(
                default=10, help_text="Monitoring interval in seconds"
            ),
        ),
    ]
