# Generated by Django 6.0.7 on 2026-09-17 09:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0005_alter_monitor_interval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("SLACK", "Slack Webhook"),
                            ("TELEGRAM", "Telegram"),
                            ("DISCORD", "Discord Webhook"),
                            ("WEBHOOK", "Custom Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        help_text="Configuration for the channel (e.g., {'webhook_url': '...'} or {'bot_token': '...', 'chat_id': '...'})"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
