# Generated by Django 6.0.7 on 2026-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0006_notificationchannel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="monitor_type",
            field=models.CharField(
                choices=[
                    ("HTTP", "HTTP"),
                    ("HTTPS", "HTTPS"),
                    ("REDIS", "REDIS"),
                    ("SMTP", "SMTP"),
                    ("CELERY", "CELERY"),
                ],
                default="HTTPS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="url",
            field=models.CharField(
                help_text="URL, IP, or connection string", max_length=255
            ),
        ),
    ]
